services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB:    joycartdb
      POSTGRES_USER:  joycart
      POSTGRES_PASSWORD: joycart
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build: .
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL:      jdbc:postgresql://db:5432/joycartdb
      SPRING_DATASOURCE_USERNAME: joycart
      SPRING_DATASOURCE_PASSWORD: joycart
    ports:
      - "8082:8082"

volumes:
  pgdata: